# ConsoleConfigLoop configuration
instancePaths:

instanceFolder: "instances"

searchModes:
  - BEST_IMPROVEMENT
  - FIRST_IMPROVEMENT

neighborhoodSkipProbabilities:
  - 0
  - 0.25
  - 0.5

localSearchMoves:
  - "insert"
  - "outOfPool"
  - "interSwap"
  - "shift"
  - "transfer"
  - "intraSwap"

timeLimit: 300

randomRunN: 1

outputDirectory: "output/parallelGrasp"

parallel: true
threads: -1