# ConsoleConfigLoop configuration
instancePaths:

instanceFolder: "real_instances"

T0Options:
  - 0.99
  - 0.995
  - 0.9999

alphaOptions:
  - 0.9
  - 0.95
  - 0.99

populationSizeOptions:
  - 1000
  - 3000
  - 6000


timeLimit: 1

randomRunN: 1

outputDirectory: "tesss/outputBee"